
# docker-compose up [-d] [--build]
# docker-compose down
# docker exec -it db bash
# docker exec -it db bash

version: '3.5'
services:
    app:
        image: agenda-scraping
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: app
        tty: true
        volumes:
            - ./log:/app/log
            - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - /dev/log:/dev/log
        networks:
            - agendanet

    db:
        image: agenda-scraping-db
        build: 
            context: .
            dockerfile: Dockerfile-MySQL
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3036"
        secrets:
            - mysqluser
            - mysqlpass
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: True
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: agenda_scraping
            MYSQL_USER_FILE: /run/secrets/mysqluser
            MYSQL_PASSWORD_FILE: /run/secrets/mysqlpass
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - agendanet
# volumes:
#     db-volume:
#         - ./mysql

networks:
    agendanet:
        driver: bridge

secrets:
    mysqluser:
        environment: "MYSQL_USER"
    mysqlpass:
        environment: "MYSQL_PASSWORD"