# Database Reset
#
# Check if there is any MYSQL env variable defined. Unset if any.
# set | grep -i mysql
#
# Delete database data (caution!!!)
# rm -rf mysql/*
#
# Stop and remove containers
# ./drm.sh
#
# Startup containers up
# ./dup.sh
#
# Log into the database container
# ./mysql.sh

version: '3.5'
services:
    job:
        image: agenda-scraping-job
        depends_on:
            - db
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: job
        tty: true
        volumes:
            - ./log:/app/log
            - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - /dev/log:/dev/log
        networks:
            - agendanet
        environment: # Exposes env vars from .env file to the service container
            - MYSQL_HOST=db
            - MYSQL_USER
            - MYSQL_PASSWORD

    db:
        image: agenda-scraping-db
        build: 
            context: .
            dockerfile: Dockerfile-MySQL
            # secrets:        # Expose it to `docker run` and `docker compose up`
            #     - mysqluser
            #     - mysqlpass
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - 3306:3036
        secrets:        # Expose it to `docker up`
            - mysqluser
            - mysqlpass
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: True
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: agenda_scraping
            MYSQL_USER_FILE: /run/secrets/mysqluser
            MYSQL_PASSWORD_FILE: /run/secrets/mysqlpass
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - agendanet
# volumes:
#     db-volume:
#         - ./mysql

networks:
    agendanet:
        driver: bridge

secrets:
    mysqluser:
        environment: "MYSQL_USER"
    mysqlpass:
        environment: "MYSQL_PASSWORD"